const config = require('../config/config');
const mongoose = require('mongoose');
const db = {};
mongoose.Promise = global.Promise;
mongoose.set('strictQuery',false);
db.mongoose = mongoose;
db.url = config.DB_URL;
db.formation= require('../api/models/formation.model')(mongoose);
db.users= require('../api/models/users.model')(mongoose);
module.exports = db;